export interface StarterTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  thumbnail: string;
  blocks: any[];
  settings: { bodyBg: string; contentBg: string; contentWidth: string };
}

const defaultSettings = { bodyBg: "#f4f4f5", contentBg: "#ffffff", contentWidth: "600" };

export const STARTER_TEMPLATES: StarterTemplate[] = [
  {
    id: "blank",
    name: "Em Branco",
    description: "Comece do zero com uma tela limpa",
    category: "Básico",
    thumbnail: "blank",
    blocks: [],
    settings: defaultSettings,
  },
  {
    id: "newsletter-modern",
    name: "Newsletter Moderna",
    description: "Layout limpo e profissional para newsletters semanais",
    category: "Newsletter",
    thumbnail: "newsletter",
    blocks: [
      { id: "h1", type: "hero", content: { bgColor: "#0f172a", bgImage: "", title: "📬 Newsletter Semanal", subtitle: "As melhores novidades da semana direto na sua caixa de entrada", buttonText: "", buttonUrl: "", buttonColor: "#0EA5E9", titleColor: "#FFFFFF", subtitleColor: "#94a3b8", padding: "48", align: "center" } },
      { id: "s1", type: "spacer", content: { height: "24" } },
      { id: "h2", type: "heading", content: { text: "Destaques da Semana", align: "left", size: "22", color: "#0f172a", weight: "700", font: "Arial" } },
      { id: "d1", type: "divider", content: { color: "#0EA5E9", height: "3", style: "solid", width: "60" } },
      { id: "it1", type: "image-text", content: { imageSrc: "https://placehold.co/280x200/0EA5E9/FFF?text=Artigo+1", imageAlt: "Destaque", imagePosition: "left", title: "Título do Artigo Principal", text: "Uma breve descrição sobre o conteúdo principal da semana. Mantenha seus leitores engajados com conteúdo relevante.", buttonText: "Ler mais", buttonUrl: "https://" } },
      { id: "d2", type: "divider", content: { color: "#e5e7eb", height: "1", style: "solid", width: "100" } },
      { id: "it2", type: "image-text", content: { imageSrc: "https://placehold.co/280x200/6366f1/FFF?text=Artigo+2", imageAlt: "Destaque 2", imagePosition: "right", title: "Segundo Destaque", text: "Mais um conteúdo relevante para compartilhar com sua audiência nesta semana.", buttonText: "Saiba mais", buttonUrl: "https://" } },
      { id: "s2", type: "spacer", content: { height: "16" } },
      { id: "sc1", type: "social", content: { facebook: "https://facebook.com", instagram: "https://instagram.com", twitter: "", linkedin: "https://linkedin.com", youtube: "", align: "center", iconSize: "32", iconStyle: "colored" } },
      { id: "f1", type: "footer", content: { text: "© 2026 Sua Empresa. Todos os direitos reservados.", address: "Rua Exemplo, 123 — São Paulo, SP", unsubscribeText: "Descadastrar", unsubscribeUrl: "{{unsubscribe_url}}", color: "#999999", bgColor: "#f8fafc" } },
    ],
    settings: { bodyBg: "#f1f5f9", contentBg: "#ffffff", contentWidth: "600" },
  },
  {
    id: "promo-offer",
    name: "Oferta Promocional",
    description: "Ideal para promoções, descontos e ofertas especiais",
    category: "Promocional",
    thumbnail: "promo",
    blocks: [
      { id: "h1", type: "hero", content: { bgColor: "#7c3aed", bgImage: "", title: "🔥 OFERTA ESPECIAL", subtitle: "Aproveite até 50% de desconto em todos os produtos", buttonText: "COMPRAR AGORA", buttonUrl: "https://", buttonColor: "#f59e0b", titleColor: "#FFFFFF", subtitleColor: "#e9d5ff", padding: "56", align: "center" } },
      { id: "s1", type: "spacer", content: { height: "16" } },
      { id: "cd1", type: "countdown", content: { date: "2026-03-31T23:59:59", title: "⏰ A oferta termina em:", bgColor: "#1e1b4b", titleColor: "#FFFFFF", numberColor: "#f59e0b" } },
      { id: "s2", type: "spacer", content: { height: "24" } },
      { id: "tc1", type: "three-columns", content: { col1: "Frete Grátis\nacima de R$99", col2: "Até 50% OFF\nem selecionados", col3: "Parcele em\naté 12x", col1Icon: "🚚", col2Icon: "💰", col3Icon: "💳" } },
      { id: "s3", type: "spacer", content: { height: "16" } },
      { id: "btn1", type: "button", content: { text: "VER OFERTAS →", url: "https://", bgColor: "#7c3aed", color: "#FFFFFF", align: "center", borderRadius: "50", size: "18", fullWidth: "false", padding: "16" } },
      { id: "s4", type: "spacer", content: { height: "8" } },
      { id: "t1", type: "text", content: { text: "Use o cupom PROMO50 no checkout", align: "center", size: "14", color: "#7c3aed", lineHeight: "1.4" } },
      { id: "f1", type: "footer", content: { text: "© 2026 Sua Empresa. Todos os direitos reservados.", address: "", unsubscribeText: "Não desejo mais receber", unsubscribeUrl: "{{unsubscribe_url}}", color: "#999", bgColor: "#f4f4f5" } },
    ],
    settings: { bodyBg: "#faf5ff", contentBg: "#ffffff", contentWidth: "600" },
  },
  {
    id: "welcome-onboarding",
    name: "Boas-vindas",
    description: "Email de boas-vindas para novos assinantes ou clientes",
    category: "Transacional",
    thumbnail: "welcome",
    blocks: [
      { id: "s0", type: "spacer", content: { height: "16" } },
      { id: "h1", type: "heading", content: { text: "Bem-vindo(a)! 🎉", align: "center", size: "32", color: "#0f172a", weight: "800", font: "Arial" } },
      { id: "t1", type: "text", content: { text: "Estamos muito felizes em tê-lo(a) conosco! Preparamos tudo para que você tenha a melhor experiência possível.", align: "center", size: "16", color: "#475569", lineHeight: "1.7" } },
      { id: "d1", type: "divider", content: { color: "#0EA5E9", height: "2", style: "solid", width: "40" } },
      { id: "s1", type: "spacer", content: { height: "8" } },
      { id: "h2", type: "heading", content: { text: "Próximos passos", align: "left", size: "20", color: "#0f172a", weight: "700", font: "Arial" } },
      { id: "l1", type: "list", content: { items: "Complete seu perfil para uma experiência personalizada\nExplore nossos recursos e funcionalidades\nConecte-se com nossa comunidade\nEntre em contato se precisar de ajuda", style: "numbered", color: "#0EA5E9", textColor: "#334155" } },
      { id: "s2", type: "spacer", content: { height: "8" } },
      { id: "btn1", type: "button", content: { text: "COMEÇAR AGORA", url: "https://", bgColor: "#0EA5E9", color: "#FFFFFF", align: "center", borderRadius: "8", size: "16", fullWidth: "false", padding: "14" } },
      { id: "s3", type: "spacer", content: { height: "16" } },
      { id: "q1", type: "quote", content: { text: "A jornada de mil milhas começa com um único passo.", author: "Lao Tzu", borderColor: "#0EA5E9", bgColor: "#f0f9ff" } },
      { id: "f1", type: "footer", content: { text: "© 2026 Sua Empresa. Todos os direitos reservados.", address: "Rua Exemplo, 123 — São Paulo, SP", unsubscribeText: "Descadastrar", unsubscribeUrl: "{{unsubscribe_url}}", color: "#999", bgColor: "#f8fafc" } },
    ],
    settings: { bodyBg: "#f0f9ff", contentBg: "#ffffff", contentWidth: "600" },
  },
  {
    id: "event-invite",
    name: "Convite para Evento",
    description: "Perfeito para webinars, conferências e eventos online",
    category: "Evento",
    thumbnail: "event",
    blocks: [
      { id: "h1", type: "hero", content: { bgColor: "#0f172a", bgImage: "", title: "Você está convidado(a)!", subtitle: "Webinar exclusivo sobre as tendências do mercado para 2026", buttonText: "GARANTIR MINHA VAGA", buttonUrl: "https://", buttonColor: "#10b981", titleColor: "#FFFFFF", subtitleColor: "#94a3b8", padding: "56", align: "center" } },
      { id: "s1", type: "spacer", content: { height: "24" } },
      { id: "tc1", type: "three-columns", content: { col1: "15 de Março\n2026", col2: "19h00\nHorário de Brasília", col3: "Online\nVia Zoom", col1Icon: "📅", col2Icon: "⏰", col3Icon: "💻" } },
      { id: "d1", type: "divider", content: { color: "#e5e7eb", height: "1", style: "solid", width: "80" } },
      { id: "h2", type: "heading", content: { text: "O que você vai aprender", align: "left", size: "20", color: "#0f172a", weight: "700", font: "Arial" } },
      { id: "l1", type: "list", content: { items: "Tendências de mercado para 2026\nEstratégias práticas de crescimento\nCasos de sucesso de empresas líderes\nSessão de perguntas e respostas ao vivo", style: "bullet", color: "#10b981", textColor: "#334155" } },
      { id: "s2", type: "spacer", content: { height: "16" } },
      { id: "btn1", type: "button", content: { text: "INSCREVA-SE GRATUITAMENTE", url: "https://", bgColor: "#10b981", color: "#FFFFFF", align: "center", borderRadius: "8", size: "16", fullWidth: "true", padding: "16" } },
      { id: "t1", type: "text", content: { text: "Vagas limitadas! Garanta já a sua participação.", align: "center", size: "13", color: "#ef4444", lineHeight: "1.4" } },
      { id: "f1", type: "footer", content: { text: "© 2026 Sua Empresa. Todos os direitos reservados.", address: "", unsubscribeText: "Descadastrar", unsubscribeUrl: "{{unsubscribe_url}}", color: "#999", bgColor: "#f4f4f5" } },
    ],
    settings: { bodyBg: "#ecfdf5", contentBg: "#ffffff", contentWidth: "600" },
  },
  {
    id: "feedback-survey",
    name: "Pesquisa de Satisfação",
    description: "Colete feedback dos seus clientes de forma elegante",
    category: "Feedback",
    thumbnail: "feedback",
    blocks: [
      { id: "s0", type: "spacer", content: { height: "24" } },
      { id: "h1", type: "heading", content: { text: "Como foi sua experiência?", align: "center", size: "28", color: "#0f172a", weight: "700", font: "Arial" } },
      { id: "t1", type: "text", content: { text: "Olá {{name}}, gostaríamos de saber sua opinião! Sua avaliação é muito importante para melhorarmos continuamente.", align: "center", size: "15", color: "#475569", lineHeight: "1.7" } },
      { id: "d1", type: "divider", content: { color: "#e5e7eb", height: "1", style: "solid", width: "60" } },
      { id: "tc1", type: "three-columns", content: { col1: "Adorei!", col2: "Bom", col3: "Pode melhorar", col1Icon: "😍", col2Icon: "😊", col3Icon: "😐" } },
      { id: "s1", type: "spacer", content: { height: "16" } },
      { id: "btn1", type: "button", content: { text: "RESPONDER PESQUISA COMPLETA", url: "https://", bgColor: "#6366f1", color: "#FFFFFF", align: "center", borderRadius: "8", size: "15", fullWidth: "false", padding: "14" } },
      { id: "t2", type: "text", content: { text: "Leva menos de 2 minutos ⏱️", align: "center", size: "13", color: "#94a3b8", lineHeight: "1.4" } },
      { id: "s2", type: "spacer", content: { height: "16" } },
      { id: "f1", type: "footer", content: { text: "© 2026 Sua Empresa. Obrigado pelo seu tempo!", address: "", unsubscribeText: "Descadastrar", unsubscribeUrl: "{{unsubscribe_url}}", color: "#999", bgColor: "#f8fafc" } },
    ],
    settings: { bodyBg: "#f5f3ff", contentBg: "#ffffff", contentWidth: "600" },
  },
  {
    id: "black-friday",
    name: "Black Friday",
    description: "Template impactante para campanhas de Black Friday",
    category: "Promocional",
    thumbnail: "blackfriday",
    blocks: [
      { id: "h1", type: "hero", content: { bgColor: "#000000", bgImage: "", title: "BLACK FRIDAY", subtitle: "As maiores ofertas do ano estão aqui! Descontos de até 70% OFF", buttonText: "🔥 VER OFERTAS", buttonUrl: "https://", buttonColor: "#ef4444", titleColor: "#FFFFFF", subtitleColor: "#fbbf24", padding: "64", align: "center" } },
      { id: "cd1", type: "countdown", content: { date: "2026-11-30T23:59:59", title: "OFERTAS TERMINAM EM:", bgColor: "#18181b", titleColor: "#fbbf24", numberColor: "#ef4444" } },
      { id: "s1", type: "spacer", content: { height: "16" } },
      { id: "tc1", type: "three-columns", content: { col1: "Eletrônicos\naté 70% OFF", col2: "Moda\naté 60% OFF", col3: "Casa\naté 50% OFF", col1Icon: "📱", col2Icon: "👗", col3Icon: "🏠" } },
      { id: "s2", type: "spacer", content: { height: "8" } },
      { id: "btn1", type: "button", content: { text: "APROVEITAR AGORA →", url: "https://", bgColor: "#ef4444", color: "#FFFFFF", align: "center", borderRadius: "50", size: "18", fullWidth: "true", padding: "18" } },
      { id: "s3", type: "spacer", content: { height: "8" } },
      { id: "t1", type: "text", content: { text: "⚡ Frete grátis em compras acima de R$149 | Parcelamento em até 12x sem juros", align: "center", size: "13", color: "#71717a", lineHeight: "1.5" } },
      { id: "f1", type: "footer", content: { text: "© 2026 Sua Loja. Promoção por tempo limitado.", address: "", unsubscribeText: "Descadastrar", unsubscribeUrl: "{{unsubscribe_url}}", color: "#71717a", bgColor: "#18181b" } },
    ],
    settings: { bodyBg: "#09090b", contentBg: "#ffffff", contentWidth: "600" },
  },
  {
    id: "product-launch",
    name: "Lançamento de Produto",
    description: "Apresente seu novo produto com estilo",
    category: "Promocional",
    thumbnail: "launch",
    blocks: [
      { id: "s0", type: "spacer", content: { height: "16" } },
      { id: "t0", type: "text", content: { text: "NOVO LANÇAMENTO", align: "center", size: "12", color: "#0EA5E9", lineHeight: "1.4" } },
      { id: "h1", type: "heading", content: { text: "Conheça o Produto X", align: "center", size: "34", color: "#0f172a", weight: "800", font: "Arial" } },
      { id: "t1", type: "text", content: { text: "O futuro chegou. Apresentamos a revolução que você estava esperando — mais rápido, mais inteligente, mais bonito.", align: "center", size: "16", color: "#64748b", lineHeight: "1.7" } },
      { id: "img1", type: "image", content: { src: "https://placehold.co/560x320/0f172a/0EA5E9?text=Produto+X", alt: "Produto X", width: "100", borderRadius: "12", link: "" } },
      { id: "s1", type: "spacer", content: { height: "8" } },
      { id: "tc1", type: "three-columns", content: { col1: "Ultra Rápido\nPerformance 2x", col2: "Design Premium\nAcabamento único", col3: "Eco Friendly\n100% reciclável", col1Icon: "⚡", col2Icon: "✨", col3Icon: "🌱" } },
      { id: "d1", type: "divider", content: { color: "#e5e7eb", height: "1", style: "solid", width: "80" } },
      { id: "btn1", type: "button", content: { text: "QUERO CONHECER", url: "https://", bgColor: "#0f172a", color: "#FFFFFF", align: "center", borderRadius: "8", size: "16", fullWidth: "false", padding: "16" } },
      { id: "t2", type: "text", content: { text: "Pré-venda exclusiva com 20% de desconto", align: "center", size: "14", color: "#0EA5E9", lineHeight: "1.4" } },
      { id: "f1", type: "footer", content: { text: "© 2026 Sua Empresa. Todos os direitos reservados.", address: "", unsubscribeText: "Descadastrar", unsubscribeUrl: "{{unsubscribe_url}}", color: "#999", bgColor: "#f8fafc" } },
    ],
    settings: { bodyBg: "#f8fafc", contentBg: "#ffffff", contentWidth: "600" },
  },
];
